### ISSUE TITLE
Factual ID: 106fb0c2-2ec6-40a6-b2c4-ca6c413a6ab8

### ISSUE THREAD

**Issue by jeff2488** [Factual/places#13]

**Comment by BradleyFactual** [comment]
[That data point](https://www.factual.com/106fb0c2-2ec6-40a6-b2c4-ca6c413a6ab8) appears to be sourced from a Foursquare checkin.

**Comment by BradleyFactual** [comment]
I put a super vote in to correct the lat/lng via Stitch. Seems perplexing that we'd choose a foursquare lat/lng as the canonical location when there is a (single) alternative source. @johnfactual for visibility.

**Comment by BradleyFactual** [comment]
![screen shot 2016-04-29 at 9 55 29 am](https://cloud.githubusercontent.com/assets/3768818/14923177/937791fa-0df0-11e6-885c-970175b77a69.png)
